const users = [
  {
    id: 1,
    name: "Abolfazl",
    lName: "Saffari",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example1@gamil.com",
    address: "Tehran",
    photoUrl: "men",
    // because of our specific api I named these values in this way that you see.
  },
  {
    id: 2,
    name: "Ahmad",
    lName: "Saffari",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example2@gamil.com",
    address: "Alborz",
    photoUrl: "men",
  },
  {
    id: 3,
    name: "Reza",
    lName: "Saffari",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example3@gamil.com",
    address: "Alborz",
    photoUrl: "men",
  },
  {
    id: 4,
    name: "Parisa",
    lName: "Nouri",
    gender: "Female",
    phone: "9192675847",
    emailAddress: "example4@gamil.com",
    address: "Zanjan",
    photoUrl: "women",
  },
  {
    id: 5,
    name: "Pouri",
    lName: "Mohammadi",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example5@gamil.com",
    address: "Zanjan",
    photoUrl: "men",
  },
  {
    id: 6,
    name: "Saleh",
    lName: "Qasemi",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example6@gamil.com",
    address: "Zanjan",
    photoUrl: "men",
  },
  {
    id: 7,
    name: "Yasamin",
    lName: "Mohammadi",
    gender: "Female",
    phone: "9192675847",
    emailAddress: "example7@gamil.com",
    address: "Zanjan",
    photoUrl: "women",
  },
  {
    id: 8,
    name: "Amir",
    lName: "Qasemi",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example8@gamil.com",
    address: "Zanjan",
    photoUrl: "men",
  },
  {
    id: 9,
    name: "Salar",
    lName: "Mohammadi",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example9@gamil.com",
    address: "Alborz",
    photoUrl: "men",
  },
  {
    id: 10,
    name: "Negar",
    lName: "Saffari",
    gender: "Female",
    phone: "9192675847",
    emailAddress: "example10@gamil.com",
    address: "Zanjan",
    photoUrl: "women",
  },
  {
    id: 11,
    name: "Marziye",
    lName: "Qasemi",
    gender: "Female",
    phone: "9192675847",
    emailAddress: "example11@gamil.com",
    address: "Zanjan",
    photoUrl: "women",
  },
  {
    id: 12,
    name: "Mona",
    lName: "Nouri",
    gender: "Female",
    phone: "9192675847",
    emailAddress: "example12@gamil.com",
    address: "Alborz",
    photoUrl: "women",
  },
  {
    id: 13,
    name: "Leyla",
    lName: "Qasemi",
    gender: "Female",
    phone: "9192675847",
    emailAddress: "example13@gamil.com",
    address: "Zanjan",
    photoUrl: "women",
  },
  {
    id: 14,
    name: "Safar",
    lName: "Honarmand",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example14@gamil.com",
    address: "Zanjan",
    photoUrl: "men",
  },
  {
    id: 15,
    name: "Jafar",
    lName: "Mohammadi",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example15@gamil.com",
    address: "Alborz",
    photoUrl: "men",
  },
  {
    id: 16,
    name: "Mohammad",
    lName: "Honarmand",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example16@gamil.com",
    address: "Zanjan",
    photoUrl: "men",
  },
  {
    id: 17,
    name: "Ali",
    lName: "Nouri",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example17@gamil.com",
    address: "Zanjan",
    photoUrl: "men",
  },
  {
    id: 18,
    name: "Koroush",
    lName: "Honarmand",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example18@gamil.com",
    address: "Alborz",
    photoUrl: "men",
  },
  {
    id: 19,
    name: "Kian",
    lName: "Honarmand",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example19@gamil.com",
    address: "Tehran",
    photoUrl: "men",
  },
  {
    id: 20,
    name: "Nima",
    lName: "Honarmand",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example20@gamil.com",
    address: "Zanjan",
    photoUrl: "men",
  },
  {
    id: 21,
    name: "Babak",
    lName: "Mohammadi",
    gender: "Male",
    phone: "9192675847",
    emailAddress: "example21@gamil.com",
    address: "Tehran",
    photoUrl: "men",
  },
  {
    id: 22,
    name: "Zari",
    lName: "Saffari",
    gender: "Female",
    phone: "9192675847",
    emailAddress: "example22@gamil.com",
    address: "Zanjan",
    photoUrl: "women",
  },
  {
    id: 23,
    name: "Tina",
    lName: "Mohammadi",
    gender: "Female",
    phone: "9192675847",
    emailAddress: "example23@gamil.com",
    address: "Tehran",
    photoUrl: "women",
  },
];
export default users;
